# defines from libfprint libraryr
VCSFW_CMD_ACE = 0xA7

BMKT_MESSAGE_HEADER_ID = 0xFE
BMKT_MESSAGE_HEADER_LEN = 4
BMKT_MESSAGE_CRC32_LEN = 4
BMKT_MESSAGE_HEADER_ID_FIELD = 0
BMKT_MESSAGE_SEQ_NUM_FIELD = 1
BMKT_MESSAGE_ID_FIELD = 2
BMKT_MESSAGE_PAYLOAD_LEN_FIELD = 3
BMKT_MESSAGE_PAYLOAD_FIELD = 4

BMKT_CMD_CONTINUOUS_IMAGE_CAPTURE = 0x01
BMKT_CMD_CONTINUOUS_IMAGE_CAPTURE_STOP = 0x04
BMKT_CMD_SENSOR_MODULE_TEST = 0x06
BMKT_CMD_SENSOR_MODULE_TEST_START = 0x08
BMKT_CMD_NEXT_TEST_REPORT_CHUNK = 0x0B
BMKT_CMD_FPS_INIT = 0x11
BMKT_CMD_GET_FPS_MODE = 0x21
BMKT_CMD_SET_SECURITY_LEVEL = 0x31
BMKT_CMD_GET_SECURITY_LEVEL = 0x34
BMKT_CMD_CANCEL_OP = 0x41
BMKT_CMD_ENROLL_USER = 0x51
BMKT_CMD_ENROLL_PAUSE = 0x52
BMKT_CMD_ENROLL_RESUME = 0x53
BMKT_CMD_ID_USER = 0x61
BMKT_CMD_VERIFY_USER = 0x65
BMKT_CMD_GET_TEMPLATE_RECORDS = 0x71
BMKT_CMD_GET_NEXT_QUERY_RESPONSE = 0x72
BMKT_CMD_GET_ENROLLED_FINGERS = 0x73
BMKT_CMD_GET_DATABASE_CAPACITY = 0x74
BMKT_CMD_DEL_USER_FP = 0x81
BMKT_CMD_DEL_FULL_DB = 0x84
BMKT_CMD_REPEAT_LAST_RSP = 0x92
BMKT_CMD_POWER_DOWN_NOTIFY = 0xA1
BMKT_CMD_GET_VERSION = 0xB1
BMKT_CMD_DISABLE_PAIRING = 0xC2
BMKT_CMD_QUERY_PAIRING = 0xC5
BMKT_CMD_SENSOR_STATUS = 0xD1
BMKT_CMD_ID_USER_IN_ORDER = 0xE1
BMKT_CMD_ID_NEXT_USER = 0xE3
BMKT_CMD_VERIFY_USER_IN_ORDER = 0xF1
BMKT_CMD_VERIFY_FINGERS_IN_ORDER = 0xF2
BMKT_CMD_GET_FINAL_RESULT = 0xE4

BMKT_EVT_FINGER_REPORT = 0x91

BMKT_EVT_FINGER_STATE_NOT_ON_SENSOR = 0x00
BMKT_EVT_FINGER_STATE_ON_SENSOR = 0x01

BMKT_RSP_CONTINUOUS_IMAGE_CAPTURE_FAIL = 0x02
BMKT_RSP_CONTINUOUS_IMAGE_CAPTURE_READY = 0x03
BMKT_RSP_CONTINUOUS_IMAGE_CAPTURE_STOPPED = 0x05
BMKT_RSP_SENSOR_MODULE_TEST_READY = 0x07
BMKT_RSP_SENSOR_MODULE_TEST_FAIL = 0x09
BMKT_RSP_SENSOR_MODULE_TEST_REPORT = 0x0A
BMKT_RSP_NEXT_TEST_REPORT_CHUNK = 0x0C
BMKT_RSP_FPS_INIT_FAIL = 0x12
BMKT_RSP_FPS_INIT_OK = 0x13
BMKT_RSP_FPS_MODE_FAIL = 0x22
BMKT_RSP_FPS_MODE_REPORT = 0x23
BMKT_RSP_SET_SECURITY_LEVEL_FAIL = 0x32
BMKT_RSP_SET_SECURITY_LEVEL_REPORT = 0x33
BMKT_RSP_GET_SECURITY_LEVEL_FAIL = 0x35
BMKT_RSP_GET_SECURITY_LEVEL_REPORT = 0x36
BMKT_RSP_CANCEL_OP_OK = 0x42
BMKT_RSP_CANCEL_OP_FAIL = 0x43
BMKT_RSP_ENROLL_READY = 0x54
BMKT_RSP_ENROLL_REPORT = 0x55
BMKT_RSP_ENROLL_PAUSED = 0x56
BMKT_RSP_ENROLL_RESUMED = 0x57
BMKT_RSP_ENROLL_FAIL = 0x58
BMKT_RSP_ENROLL_OK = 0x59
BMKT_RSP_CAPTURE_COMPLETE = 0x60
BMKT_RSP_ID_READY = 0x62
BMKT_RSP_ID_FAIL = 0x63
BMKT_RSP_ID_OK = 0x64
BMKT_RSP_VERIFY_READY = 0x66
BMKT_RSP_VERIFY_FAIL = 0x67
BMKT_RSP_VERIFY_OK = 0x68
BMKT_RSP_TEMPLATE_RECORDS_REPORT = 0x75
BMKT_RSP_QUERY_RESPONSE_COMPLETE = 0x76
BMKT_RSP_GET_ENROLLED_FINGERS_REPORT = 0x77
BMKT_RSP_DATABASE_CAPACITY_REPORT = 0x78
BMKT_RSP_QUERY_FAIL = 0x79
BMKT_RSP_DEL_USER_FP_FAIL = 0x82
BMKT_RSP_DEL_USER_FP_OK = 0x83
BMKT_RSP_DEL_FULL_DB_FAIL = 0x85
BMKT_RSP_DEL_FULL_DB_OK = 0x86
BMKT_RSP_DELETE_PROGRESS = 0x87
BMKT_RSP_REPEAT_LAST_BMKT_RSP_FAIL = 0x93
BMKT_RSP_POWER_DOWN_READY = 0xA2
BMKT_RSP_POWER_DOWN_FAIL = 0xA3
BMKT_RSP_VERSION_INFO = 0xB2
BMKT_RSP_GET_VERSION_FAIL = 0xB3
BMKT_RSP_GENERAL_ERROR = 0xC1
BMKT_RSP_DISABLE_PAIRING_FAIL = 0xC3
BMKT_RSP_DISABLE_PAIRING_OK = 0xC4
BMKT_RSP_QUERY_PAIRING_FAIL = 0xC6
BMKT_RSP_SENSOR_PAIRING_REPORT = 0xC7
BMKT_RSP_SENSOR_STATUS_REPORT = 0xD2
BMKT_RSP_SENSOR_STATUS_FAIL = 0xD3
BMKT_RSP_SEND_NEXT_USER_ID = 0xE2
BMKT_RSP_RETRIEVE_FINAL_RESULT_FAIL = 0xE5

bmkt_resp = {
    0x02: "BMKT_RSP_CONTINUOUS_IMAGE_CAPTURE_FAIL",
    0x03: "BMKT_RSP_CONTINUOUS_IMAGE_CAPTURE_READY",
    0x05: "BMKT_RSP_CONTINUOUS_IMAGE_CAPTURE_STOPPED",
    0x07: "BMKT_RSP_SENSOR_MODULE_TEST_READY",
    0x09: "BMKT_RSP_SENSOR_MODULE_TEST_FAIL",
    0x0A: "BMKT_RSP_SENSOR_MODULE_TEST_REPORT",
    0x0C: "BMKT_RSP_NEXT_TEST_REPORT_CHUNK",
    0x12: "BMKT_RSP_FPS_INIT_FAIL",
    0x13: "BMKT_RSP_FPS_INIT_OK",
    0x22: "BMKT_RSP_FPS_MODE_FAIL",
    0x23: "BMKT_RSP_FPS_MODE_REPORT",
    0x32: "BMKT_RSP_SET_SECURITY_LEVEL_FAIL",
    0x33: "BMKT_RSP_SET_SECURITY_LEVEL_REPORT",
    0x35: "BMKT_RSP_GET_SECURITY_LEVEL_FAIL",
    0x36: "BMKT_RSP_GET_SECURITY_LEVEL_REPORT",
    0x42: "BMKT_RSP_CANCEL_OP_OK",
    0x43: "BMKT_RSP_CANCEL_OP_FAIL",
    0x54: "BMKT_RSP_ENROLL_READY",
    0x55: "BMKT_RSP_ENROLL_REPORT",
    0x56: "BMKT_RSP_ENROLL_PAUSED",
    0x57: "BMKT_RSP_ENROLL_RESUMED",
    0x58: "BMKT_RSP_ENROLL_FAIL",
    0x59: "BMKT_RSP_ENROLL_OK",
    0x60: "BMKT_RSP_CAPTURE_COMPLETE",
    0x62: "BMKT_RSP_ID_READY",
    0x63: "BMKT_RSP_ID_FAIL",
    0x64: "BMKT_RSP_ID_OK",
    0x66: "BMKT_RSP_VERIFY_READY",
    0x67: "BMKT_RSP_VERIFY_FAIL",
    0x68: "BMKT_RSP_VERIFY_OK",
    0x75: "BMKT_RSP_TEMPLATE_RECORDS_REPORT",
    0x76: "BMKT_RSP_QUERY_RESPONSE_COMPLETE",
    0x77: "BMKT_RSP_GET_ENROLLED_FINGERS_REPORT",
    0x78: "BMKT_RSP_DATABASE_CAPACITY_REPORT",
    0x79: "BMKT_RSP_QUERY_FAIL",
    0x82: "BMKT_RSP_DEL_USER_FP_FAIL",
    0x83: "BMKT_RSP_DEL_USER_FP_OK",
    0x85: "BMKT_RSP_DEL_FULL_DB_FAIL",
    0x86: "BMKT_RSP_DEL_FULL_DB_OK",
    0x87: "BMKT_RSP_DELETE_PROGRESS",
    0x93: "BMKT_RSP_REPEAT_LAST_BMKT_RSP_FAIL",
    0xA2: "BMKT_RSP_POWER_DOWN_READY",
    0xA3: "BMKT_RSP_POWER_DOWN_FAIL",
    0xB2: "BMKT_RSP_VERSION_INFO",
    0xB3: "BMKT_RSP_GET_VERSION_FAIL",
    0xC1: "BMKT_RSP_GENERAL_ERROR",
    0xC3: "BMKT_RSP_DISABLE_PAIRING_FAIL",
    0xC4: "BMKT_RSP_DISABLE_PAIRING_OK",
    0xC6: "BMKT_RSP_QUERY_PAIRING_FAIL",
    0xC7: "BMKT_RSP_SENSOR_PAIRING_REPORT",
    0xD2: "BMKT_RSP_SENSOR_STATUS_REPORT",
    0xD3: "BMKT_RSP_SENSOR_STATUS_FAIL",
    0xE2: "BMKT_RSP_SEND_NEXT_USER_ID",
    0xE5: "BMKT_RSP_RETRIEVE_FINAL_RESULT_FAIL",
}


def bmkt_resp_get_str(resp: int) -> str:
    if resp in bmkt_resp:
        return bmkt_resp[resp]
    return "bmkt unknown resp"
