
#define VCSFW_STORAGE_TUDOR_PART_ID_SSFS 1
#define VCSFW_STORAGE_TUDOR_PART_ID_HOST 2

#define OBJ_TYPE_USERS 1
#define OBJ_TYPE_TEMPLATES 2
#define OBJ_TYPE_PAYLOADS 3

#define CONT_TAG_PROPERTY_ID 4
#define CONT_TAG_PROPERTY_DATA 5

#define HOST_TAG_VERSION 1
#define HOST_TAG_PAIRED_DATA 2

#define PAIR_DATA_TAG_VERSION 0
#define PAIR_DATA_TAG_HOST_CERT 1
#define PAIR_DATA_TAG_PRIVATE_KEY 2
#define PAIR_DATA_TAG_SENSOR_CERT 3
#define PAIR_DATA_TAG_PUB_KEY_SEC_DATA 4
#define PAIR_DATA_TAG_SSI_STORAGE_PSK_ID 5

#define ENROLL_TAG_TUID 0
#define ENROLL_TAG_USERID 1
#define ENROLL_TAG_SUBID 2

#define EV_FINGER_DOWN 1
#define EV_FINGER_UP 2
#define EV_FRAME_READY 24

#define MIS_IMAGE_METRICS_IPL_FINGER_COVERAGE 0x1
#define MIS_IMAGE_METRICS_IMG_QUALITY 0x10000

#define IMAGE_QUALITY_THRESHOLD 50
