
#define VCSFW_STORAGE_TUDOR_PART_ID_SSFS 1
#define VCSFW_STORAGE_TUDOR_PART_ID_HOST 2

#define OBJ_TYPE_USERS 1
#define OBJ_TYPE_TEMPLATES 2
#define OBJ_TYPE_PAYLOADS 3

#define MIS_IMAGE_METRICS_IPL_FINGER_COVERAGE 0x1
#define MIS_IMAGE_METRICS_IPL_FINGER_COVERAGE_DATA_SIZE 4
#define MIS_IMAGE_METRICS_IMG_QUALITY 0x10000
#define MIS_IMAGE_METRICS_IMG_QUALITY_DATA_SIZE 8

#define IMAGE_QUALITY_THRESHOLD 50

#define PROVISION_STATE_PROVISIONED 3

typedef enum {
   NO_EVENTS = 0,
   EV_FINGER_DOWN = 1,
   EV_FINGER_UP = 2,
   /*unknown and seemingly unused events*/
   EV_3 = 3,
   EV_4 = 4,
   EV_5 = 5,
   EV_6 = 6,
   EV_7 = 7,
   EV_8 = 8,
   EV_9 = 9,
   EV_FRAME_READY = 24,
} sensor_event_type_t;
